name: mqtt_helper
description: "mqtt_helper is a Flutter package that simplifies MQTT integration, reducing boilerplate code and providing a convenient layer on top of mqtt_client."

version: 1.0.2

repository: https://github.com/Jatin5120/mqtt_helper/

documentation: https://pub.dev/documentation/mqtt_helper/

issue_tracker: https://github.com/Jatin5120/mqtt_helper/issues/

homepage: https://portfolio-5120.web.app/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mqtt_client: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - network
  - mqtt
  - iot
  - messaging
  - client
